apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-serving.name" . }}
    component: serving
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application-default.yaml: |
    feast:
      core-host: {{ .Release.Name }}-feast-core
      
      stores:
      - name: online
        type: REDIS 
        config:
          host: {{ .Release.Name }}-redis-master
          port: 6379
        subscriptions:
        - name: "*"
          project: "*"
          version: "*"
      
      job_store:
        redis_host: {{ .Release.Name }}-redis-master
        redis_port: 6379

  application-override.yaml: |
{{- toYaml (index .Values "application-override.yaml") | nindent 4 }}    
