apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-statsd-exporter.fullname" . }}-config
  labels:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  statsd_mappings.yaml: |
{{- toYaml (index .Values "statsd_mappings.yaml") | nindent 4 }}
