apiVersion: v1
kind: Service
metadata:
{{- if .Values.metricsService.annotations }}
  annotations:
{{ toYaml .Values.metricsService.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus-statsd-exporter.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.metricsService.labels }}
{{ toYaml .Values.metricsService.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus-statsd-exporter.fullname" . }}-metrics
spec:
{{- if .Values.metricsService.clusterIP }}
  clusterIP: {{ .Values.metricsService.clusterIP }}
{{- end }}
{{- if .Values.metricsService.externalIPs }}
  externalIPs:
{{ toYaml .Values.metricsService.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.metricsService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metricsService.loadBalancerIP }}
{{- end }}
{{- if .Values.metricsService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.metricsService.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.port }}
      protocol: TCP
      targetPort: 9102
{{- if (and (eq .Values.metricsService.type "NodePort") (not (empty .Values.metricsService.nodePort))) }}
      nodePort: {{.Values.metricsService.nodePort}}
{{ end }}
  selector:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    release: {{ .Release.Name }}
  type: "{{ .Values.metricsService.type }}"

---

apiVersion: v1
kind: Service
metadata:
{{- if .Values.statsdService.annotations }}
  annotations:
{{ toYaml .Values.statsdService.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus-statsd-exporter.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.statsdService.labels }}
{{ toYaml .Values.statsdService.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus-statsd-exporter.fullname" . }}-statsd
spec:
{{- if .Values.statsdService.clusterIP }}
  clusterIP: {{ .Values.statsdService.clusterIP }}
{{- end }}
{{- if .Values.statsdService.externalIPs }}
  externalIPs:
{{ toYaml .Values.statsdService.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.statsdService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.statsdService.loadBalancerIP }}
{{- end }}
{{- if .Values.statsdService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.statsdService.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: statsd
      port: {{ .Values.statsdService.port }}
      protocol: {{ .Values.statsdService.protocol }}
      targetPort: {{ .Values.statsdService.port }}
{{- if (and (eq .Values.statsdService.type "NodePort") (not (empty .Values.statsdService.nodePort))) }}
      nodePort: {{.Values.statsdService.nodePort}}
{{ end }}
  selector:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    release: {{ .Release.Name }}
  type: "{{ .Values.statsdService.type }}"